### ISSUE TITLE
Add tag v0.0.2 please on commit 3e0f0afdc261

### ISSUE THREAD

**Issue by vonhenry** [filecoin-project/go-paramfetch#11]
it's used at https://github.com/vonhenry/lotus/blob/774e06843692bd2d50a4834c71d7e5389f8646d7/go.mod#L36,

without the tag, it will compile fail

**Comment by gaolizhou** [comment]
met same issue

**Comment by Stebalien** [comment]
I'm not sure what happened here but, unfortunately, we can't fix this now given https://github.com/filecoin-project/go-paramfetch/releases/tag/v0.0.2. And I'm _guessing_ that nobody cares at this point.
