### ISSUE TITLE
Checksum mismatch in param file, and the checksum code of the same file is different each time it runs.

### ISSUE THREAD

**Issue by nzy0x00** [filecoin-project/go-paramfetch#12]
The command "lotus-miner fetch-params 32GiB" failed with error "Checksum mismatch in param file".
I've tried many times, it always failed. Because it takes too much time, I manually downloaded the file and put it in the folder.
But for the same file, the checksum code of each run is different.
Here are the results of my two runs.

`go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:87	checksum mismatch in param file /data/.parameter_cache/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.params, 1d206040fe8bd9bf41d53ccabaf12846 != 6a388072a518cf46ebd661f5cc46900a`

`go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:87	checksum mismatch in param file /data/.parameter_cache/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.params, 7a153bb7ebfbb36bc2db846634087c78 != 6a388072a518cf46ebd661f5cc46900a`

**Comment by magik6k** [comment]
This is likely a CPU/memory issue (observed this on my setup). Try reverting bios settings to defaults, disabling OC/memory XMP. If that doesn't help try running something like memtest/other hardware checks.

**Comment by nzy0x00** [comment]
Thank you very much, I tested it on another computer and it worked.
